version: '3'
services:
  vkbot:
    build: .
    env_file:
      - secret.env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: vkbot
      POSTGRES_USER: vk_bot_lab
      POSTGRES_PASSWORD: Qw123456
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vk_bot_lab -d vkbot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
